#!/bin/bash

screens=( $(xrandr -q | awk '/^[A-Za-z][A-Za-z]*[0-9-]* connected/ { print $1 }') )
primary=$(xrandr -q | awk '/^[A-Za-z][A-Za-z]*[0-9-]* connected primary/ { print $1 }')

i=0
cur=0
for s in ${screens[@]}; do
  if [[ "$s" == "$primary" ]]; then
    cur=$i
  fi
  i=$(( i + 1 ))
done
count=$i

next=$(( ($cur + 1) % $count ))
nextscreen=${screens[$next]}

switch-screen -p $nextscreen
