#!/bin/bash

CMDNAME="switch-screen"

_get_screens() {
  xrandr -q | awk '/^[A-Za-z][A-Za-z]*[0-9-]* (dis)?connected / { print $1 }'
}

_get_screen() {
  local entry=$1
  _get_screens | grep -i "^$entry\$"
}

_reload_desktop() {
  systemctl --user restart wallpaper
}

_list_screens() {
  xrandr -q | awk '/^[A-Za-z][A-Za-z]*[0-9-]* connected / {
    printf $1" ";
    getline;
    printf $1" ";
    if(match($2,/\*/,m)) printf "ON";
    printf"\n"
  }' | column -t
}

_auto_biggest() {
  selection=$(_list_screens | awk '{ split($2,d,"x"); print d[1]*d[2]" "$1" "$3 }' | sort -nr | head -n1)
  if ! grep -q ON <<<$selection; then
    _main -p $(cut -d' ' -f2 <<<$selection)
  fi
}

_auto() {
  local policy="$1"
  case "$policy" in
    biggest) _auto_biggest;;
    *)       echo "Invalid policy \"$policy\".";;
  esac
  exit
}

_cli_error() {
  echo "Type \"$CMDNAME --help\" to see usage." >&2
  exit 1
}

_help() {
  echo "This command is a wrapper around xrandr to simplify screen management.

Usage:
  switch-screen -L
  switch-screen [-d] [--dry-run] -p SCREEN0 [-l SCREEN1] [-r ...]
  switch-screen -A biggest

Options:
  -L  --list     List screens
  -A  --auto     Turn on/off screen with a defined policy

  -p  --primary  Select the first screen (mandatory)
  -l  --left     Select the screen on the left
  -t  --top      Select the screen on the top
  -b  --bottom   Select the screen on the bottom
  -r  --right    Select the screen on the right

  -h  --help     Print this help message
  -d  --debug    Enable debuging messages
      --dry-run  Print the xrandr command and exit

Examples:
  switch-screen -L                   List all screens connected
  switch-screen -p hdmi-1            Use HDMI-1 screen and turn off all others screens
  switch-screen -p hdmi-1 -l lvds-1  Use HDMI-1 as a main screen and put LVDS-1 as a
                                     second screen on the left"
  exit 1
}

_main() {
  SHORT=hdLp:t:l:b:r:A:
  LONG=help,debug,list,dry-run,primary:,top:,left:,bottom:,right:,auto:

  # Print usage when no options are set
  if [[ $# == 0 ]]; then
    _cli_error
  fi

  # - Temporarily store output to be able to check for errors
  # - Activate advanced mode getopt quoting e.g. via “--options”
  # - Pass arguments only via   -- "$@"   to separate them correctly
  PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$CMDNAME" -- "$@")
  if [[ $? != 0 ]]; then
    echo
    _cli_error
    exit 2
  fi
  # use eval with "$PARSED" to properly handle the quoting
  eval set -- "$PARSED"

  local auto

  # now enjoy the options in order and nicely split until we see --
  while true; do
    case "$1" in
      -d|--debug)
        debug=y
        shift
        ;;
      -h|--help)
        _help
        shift
        ;;
      --dry-run)
        dry_run=y
        shift
        ;;
      -L|--list)
        list=y
        shift
        ;;
      -A|--auto)
        auto="$2"
        shift 2
        ;;
      -p|--primary)
        primary_screen="$2"
        shift 2
        ;;
      -t|--top)
        top_screen="$2"
        shift 2
        ;;
      -l|--left)
        left_screen="$2"
        shift 2
        ;;
      -b|--bottom)
        bottom_screen="$2"
        shift 2
        ;;
      -r|--right)
        right_screen="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *)
        cli_error
        break
        ;;
      esac
  done

  if [[ "$list" == "y" ]]; then
    _list_screens
    exit
  fi

  if [[ -n "$auto" ]]; then
    _auto "$auto"
  fi

  # If we select --primary so we want change screen layout
  if [[ -n "$primary_screen" ]]; then
    declare -a used_screen unused_screen cmd

    cmd[0]=xrandr

    # Handle primary screen
    screen=$(_get_screen $primary_screen)
    if [[ $? != 0 ]]; then
      echo "Unrecognized screen: $primary_screen"
      exit 1
    fi
    [[ "$debug" == "y" ]] && echo "Primary screen: $screen"
    primary_screen=$screen
    cmd+=("--output $screen --auto --primary")
    used_screen+=($screen)

    # Handle side screens
    for pos in left top bottom right; do
      raw_screen=$(eval "echo \$${pos}_screen")
      if [[ -n "$raw_screen" ]]; then
        screen=$(_get_screen $raw_screen)
        if [[ $? != 0 ]]; then
          echo "Unrecognized screen: $screen"
          exit 1
        fi
        [[ "$debug" == "y" ]] && echo "Side screen ($pos): $screen"
        opt=""
        case "$pos" in
          left)   opt=--left-of  ;;
          top)    opt=--above    ;;
          bottom) opt=--below    ;;
          right)  opt=--right-of ;;
        esac
        cmd+=("--output $screen $opt $primary_screen --auto")
        used_screen+=($screen)
      fi
    done

    # Handle unused screen
    unused_screen=$(printf '%s\n%s\n' "${used_screen[@]}" "$(_get_screens)" | sort | uniq -u)
    [[ "$debug" == "y" ]] && echo "Unused screens: $(tr '\n' ' ' <<<$unused_screen)"
    for scr in $unused_screen; do
      cmd+=("--output $scr --off")
    done

    # Execute xrandr command
    if [[ "$debug" == "y" ]] || [[ "$dry_run" == "y" ]]; then
      echo "Command: ${cmd[@]}"
    fi
    [[ "$dry_run" != "y" ]] && ${cmd[@]} && _reload_desktop
  fi
}

_main $@
