#!/bin/bash

CMDNAME="switch-screen"

_get_screens() {
  xrandr -q | awk '/^[A-Za-z][A-Za-z]*[0-9-]* connected / { print $1 }'
}

_get_screen() {
  local entry=$1
  _get_screens | grep -i "^$entry\$"
}

_reload_desktop() {
  systemctl --user restart wallpaper
}

_list_screens() {
  xrandr -q | awk '/^[A-Za-z][A-Za-z]*[0-9-]* connected / {
    printf $1" ";
    getline;
    printf $1" ";
    if(match($2,/\*/,m)) printf "ON";
    printf"\n"
  }' | column -t
}

_usage() {
  echo "This command is a wrapper around xrandr to simplify screen management.

Usage:
  switch-screen -L
  switch-screen [-d] [--dry-run] -p SCREEN0 [-l SCREEN1] [-r ...]

Options:
  -L  --list     List screens

  -p  --primary  Select the first screen (mandatory)
  -l  --left     Select the screen on the left
  -t  --top      Select the screen on the top
  -b  --bottom   Select the screen on the bottom
  -r  --right    Select the screen on the right
  -d  --debug    Enable debuging messages
      --dry-run  Print the xrandr command and exit

Exemples:
  switch-screen -L                   List all screens connected
  switch-screen -p hdmi-1            Use HDMI-1 screen and turn off all others screens
  switch-screen -p hdmi-1 -l lvds-1  Use HDMI-1 as a main screen and put LVDS-1 as a
                                     second screen on the left"
  exit 1
}

_main() {
  SHORT=dLp:t:l:b:r:
  LONG=debug,list,dry-run,primary:,top:,left:,bottom:,right:

  # Print usage when no options are set
  if [[ $# == 0 ]]; then
    _usage
  fi

  # - Temporarily store output to be able to check for errors
  # - Activate advanced mode getopt quoting e.g. via “--options”
  # - Pass arguments only via   -- "$@"   to separate them correctly
  PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$CMDNAME" -- "$@")
  if [[ $? != 0 ]]; then
    echo
    _usage
    exit 2
  fi
  # use eval with "$PARSED" to properly handle the quoting
  eval set -- "$PARSED"

  # now enjoy the options in order and nicely split until we see --
  while true; do
    case "$1" in
      -d|--debug)
        debug=y
        shift
        ;;
      --dry-run)
        dry_run=y
        shift
        ;;
      -L|--list)
        list=y
        shift
        ;;
      -p|--primary)
        primary_screen="$2"
        shift 2
        ;;
      -t|--top)
        top_screen="$2"
        shift 2
        ;;
      -l|--left)
        left_screen="$2"
        shift 2
        ;;
      -b|--bottom)
        bottom_screen="$2"
        shift 2
        ;;
      -r|--right)
        right_screen="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *)
        _usage
        ;;
      esac
  done

  if [[ "$list" == "y" ]]; then
    _list_screens
    exit
  fi

  # If we select --primary so we want change screen layout
  if [[ -n "$primary_screen" ]]; then
    declare -a used_screen unused_screen cmd

    cmd[0]=xrandr

    # Handle primary screen
    screen=$(_get_screen $primary_screen)
    if [[ $? != 0 ]]; then
      echo "Unrecognized screen: $primary_screen"
      exit 1
    fi
    [[ "$debug" == "y" ]] && echo "Primary screen: $screen"
    primary_screen=$screen
    cmd+=("--output $screen --auto --primary")
    used_screen+=($screen)

    # Handle side screens
    for pos in left top bottom right; do
      raw_screen=$(eval "echo \$${pos}_screen")
      if [[ -n "$raw_screen" ]]; then
        screen=$(_get_screen $raw_screen)
        if [[ $? != 0 ]]; then
          echo "Unrecognized screen: $screen"
          exit 1
        fi
        [[ "$debug" == "y" ]] && echo "Side screen ($pos): $screen"
        opt=""
        case "$pos" in
          left)   opt=--left-of  ;;
          top)    opt=--above    ;;
          bottom) opt=--below    ;;
          right)  opt=--right-of ;;
        esac
        cmd+=("--output $screen $opt $primary_screen --auto")
        used_screen+=($screen)
      fi
    done

    # Handle unused screen
    unused_screen=$(echo -e "${used_screen[@]}\n$(_get_screens)" | tr " " "\n" | sort | uniq -c | awk '$1 == 1 { print $2 }')
    [[ "$debug" == "y" ]] && echo "Unused screens: $(tr '\n' ' ' <<<$unused_screen)"
    for scr in $unused_screen; do
      cmd+=("--output $scr --off")
    done

    # Execute xrandr command
    if [[ "$debug" == "y" ]] || [[ "$dry_run" == "y" ]]; then
      echo "Command: ${cmd[@]}"
    fi
    [[ "$dry_run" != "y" ]] && ${cmd[@]} && _reload_desktop
  fi
}

_main $@
