#!/usr/bin/env python

import re
import os
import sys
from subprocess import Popen, PIPE

reg = "Battery %d: (\w+), (\d+)%%(, (\d+:\d+):\d+ .+)?"
bat_number = int(os.getenv("BLOCK_INSTANCE", 0) or 0)
# icons: plug, battery full to empty
icons = list(u"\uf1e6\uf240\uf241\uf242\uf243\uf244")
colors = ("#c9dfe2", "#c9dfe2", "#a8ff00", "#fff600", "#ffae00", "#ff0000")
threshold = (100, 80, 60, 40, 20, 0)

p = Popen(["acpi", "-b"], stdout=PIPE)
p.wait()
r = p.stdout.read().strip().splitlines()

for l in r:
    pattern = re.compile(reg % bat_number)
    state, percentage, _, remaining = pattern.match(l).groups()
    percentage = int(percentage)
    break

code = 0
if state == "Discharging":
    i = 0
    while percentage <= threshold[i]:
        i += 1
        code += 1

    power = int(open("/sys/class/power_supply/BAT1/power_now").read()) / 10e5

text = u"{} {}%".format(icons[code], percentage)

if remaining:
    text += " / " + remaining

if state == "Discharging":
    text += " / %d W" % round(power)

print text.encode("utf-8")
print text.encode("utf-8")
print colors[code]

if percentage <= 5:
    sys.exit(33)
