#!/usr/bin/env python3

import time
import os
import os.path
import sys
from subprocess import call


def set_wallpaper(path):
    call(['feh', '--no-fehbg', '--bg-scale', path])


def main():
    if len(sys.argv) != 2:
        print("Usage: i3-wallpaper [directory]")
        sys.exit(1)

    wallpaper_dir = os.path.abspath(os.path.expanduser(sys.argv[1]))

    if not os.path.isdir(wallpaper_dir):
        print("Error: the path provided is not a directory.")
        sys.exit(1)

    while True:
        choices = sorted(os.listdir(wallpaper_dir))
        for path in choices:
            set_wallpaper(os.path.join(wallpaper_dir, path))
            time.sleep(60)


if __name__ == "__main__":
    main()
